version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme           # ✅ 設定 elastic 使用者密碼
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - library_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_internal       # ✅ 加上帳密供 Kibana 使用
      - ELASTICSEARCH_PASSWORD=kibana123

    depends_on:
      - elasticsearch
    networks:
      - library_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: uTXa3ZqJ1DMHR9WypFboLgYcKsvfNe58
      MYSQL_DATABASE: library
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - library_network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  elasticsearch_data:
    driver: local
  mysql_data:
    driver: local

networks:
  library_network:
    driver: bridge
